# Generated by Django 3.2.15 on 2022-09-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0008_action_index'),
        ('auditlog', '0010_alter_logentry_timestamp'),
    ]

    operations = [
    ]
