# Generated by Django 3.2.15 on 2022-10-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0011_merge_20220930_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
