# Generated by Django 3.2.15 on 2022-10-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0011_logentry_serialized_data'),
        ('auditlog', '0012_alter_logentry_id'),
    ]

    operations = [
    ]
